image:
 registry: cr.weaviate.io
 tag: 1.25.6
 repo: semitechnologies/weaviate
 pullPolicy: IfNotPresent
 pullSecrets: []

command: ["/bin/weaviate"]
args:
 - "--host"
 - "0.0.0.0"
 - "--port"
 - "8080"
 - "--scheme"
 - "http"
 - "--config-file"
 - "/weaviate-config/conf.yaml"
 - --read-timeout=60s
 - --write-timeout=60s

initContainers:
 sysctlInitContainer:
  enabled: true
  sysctlVmMaxMapCount: 524288
  image:
   registry: docker.io
   repo: alpine
   tag: latest
   pullPolicy: IfNotPresent
 ensureFileOwnershipContainer:
  enabled: false

 extraInitContainers: {}

replicas: 1

podManagementPolicy: Parallel
updateStrategy:
 type: RollingUpdate
resources: {}

securityContext: {}

containerSecurityContext: {}

serviceAccountName:

clusterDomain: cluster.local.

storage:
 size: 32Gi
 storageClassName: ""

service:
 name: bachmatch-weaviate
 ports:
  - name: http
    protocol: TCP
    port: 80
    # Target port is going to be the same for every port
 type: LoadBalancer
 loadBalancerSourceRanges: []
 clusterIP:
 annotations: {}

grpcService:
 enabled: true
 name: bachmatch-weaviate-grpc
 ports:
  - name: grpc
    protocol: TCP
    port: 50051
    # Target port is going to be the same for every port
 type: LoadBalancer
 loadBalancerSourceRanges: []
 clusterIP:
 annotations: {}

serviceMonitor:
 enabled: false
 interval: 30s
 scrapeTimeout: 10s

startupProbe:
 enabled: false
 probeType: httpGet
 probe:
  httpGet:
   path: /v1/.well-known/ready
   port: 8080
 initialDelaySeconds: 300
 periodSeconds: 60
 failureThreshold: 50
 successThreshold: 1
 timeoutSeconds: 3

livenessProbe:
 probeType: httpGet
 probe:
  httpGet:
   path: /v1/.well-known/live
   port: 8080
 initialDelaySeconds: 900
 periodSeconds: 10
 failureThreshold: 30
 successThreshold: 1
 timeoutSeconds: 3

readinessProbe:
 probeType: httpGet
 probe:
  httpGet:
   path: /v1/.well-known/ready
   port: 8080
 initialDelaySeconds: 3
 periodSeconds: 10
 failureThreshold: 3
 successThreshold: 1
 timeoutSeconds: 3

terminationGracePeriodSeconds: 600

authentication:
 anonymous_access:
  enabled: true
 oidc:
  enabled: false
  # issuer: ''
  # username_claim: ''
  # groups_claim: ''
  # client_id: ''

authorization:
 admin_list:
  enabled: false
  # users:
  # - admin_user1
  # - admin_user2
  # - api-key-user-admin
  # read_only_users:
  # - readonly_user1
  # - readonly_user2
  # - api-key-user-readOnly

query_defaults:
 limit: 200
debug: false

env:
 CLUSTER_GOSSIP_BIND_PORT: 7000
 CLUSTER_DATA_BIND_PORT: 7001

 GOGC: 100

 PROMETHEUS_MONITORING_ENABLED: false
 PROMETHEUS_MONITORING_GROUP: false

 QUERY_MAXIMUM_RESULTS: 100000

 TRACK_VECTOR_DIMENSIONS: false

 REINDEX_VECTOR_DIMENSIONS_AT_STARTUP: false

custom_config_map:
 enabled: false
 name: "custom-config"

affinity:
 podAntiAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
   - weight: 1
     podAffinityTerm:
      topologyKey: "kubernetes.io/hostname"
      labelSelector:
       matchExpressions:
        - key: "app"
          operator: In
          values:
           - weaviate

priorityClassName: ""
globalPriorityClassName: ""
