apiVersion: skaffold/v4beta9
kind: Config
metadata:
 name: dev-cluster
build:
 artifacts:
  - image: bachmatch/bachmatch
    context: web-app
    docker:
     dockerfile: Dockerfile
  - image: bachmatch/bachmatch-spark
    context: spark-app
    docker:
     dockerfile: Dockerfile
manifests:
 rawYaml:
  - k8s/kafka-topic.yaml
  - k8s/bachmatch-spark.yaml
  - k8s/bachmatch-web.yaml
